name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_13.png
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/coin_1_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/coin_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/images/egg_kind_of_toast.png
  - assets/images/image_13.png
  - assets/images/frechpress_1.jpeg
  - assets/images/sweet_toast.png
  - assets/images/picollo.png
  - assets/images/black_coffee.png
  - assets/images/choco_latte.png
  - assets/images/matcha_latte.jpeg
  - assets/images/savory_toast.png
  - assets/images/espresso.jpeg
  - assets/images/v_60.jpeg
  - assets/images/almond_croissant.jpeg
  - assets/images/butterscotch_latte_1.png
  - assets/images/sweet_chesee_toast.png
  - assets/images/cafe_latte.png
  - assets/images/feelectric_signature_toast.png
  - assets/images/choco_latte_1.jpeg
  - assets/images/cappucino.png
  - assets/images/rose_balck_tea.png
  - assets/images/doppio.jpeg
  - assets/images/aeropress_1.jpeg
  - assets/images/butterscotch_latte_2.jpeg
  - assets/images/danish_blueberry.png
  - assets/images/sweet_jam_toast.png
  - assets/images/rectangle_51.jpeg
  - assets/images/plain_croissant.jpeg
  - assets/images/rectangle_472.png
  - assets/images/rectangle_47.jpeg
  - assets/images/aeropress.jpeg
  - assets/images/matcha_latte_1.png
  - assets/images/choco_lava.png
  - assets/images/rectangle_471.jpeg
  - assets/images/butterscotch_latte.png
  - assets/images/v_601.jpeg
  - assets/images/frechpress.jpeg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/images/rectangle_33.jpeg
  - assets/images/image_13.png
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/images/image_13.png
  - assets/vectors/icon_19_x2.svg
  - assets/vectors/icon_20_x2.svg
  - assets/vectors/icon_13_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/icon_11_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/icon_4_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/images/image_13.png
  - assets/vectors/vector_39_x2.svg
  - assets/images/image_13.png
  - assets/vectors/vector_65_x2.svg
  - assets/images/image_13.png
  - assets/vectors/vector_12_x2.svg
  - assets/images/image_13.png
  - assets/vectors/vector_58_x2.svg
  - assets/images/rectangle_110.jpeg
  - assets/images/image_13.png
  - assets/vectors/dictation_2_x2.svg
  - assets/vectors/rectangle_11_x2.svg
  - assets/vectors/shift_1_x2.svg
  - assets/vectors/emoji_1_x2.svg
  - assets/vectors/rectangle_5_x2.svg
  - assets/vectors/rectangle_2_x2.svg
  - assets/vectors/container_x2.svg
  - assets/images/rectangle_472.png
  - assets/images/image_13.png
  - assets/vectors/rectangle_801_x2.svg
  - assets/vectors/rectangle_94_x2.svg
  - assets/vectors/rectangle_90_x2.svg
  - assets/vectors/rectangle_821_x2.svg
  - assets/vectors/rectangle_85_x2.svg
  - assets/vectors/rectangle_89_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/rectangle_96_x2.svg
  - assets/vectors/rectangle_831_x2.svg
  - assets/vectors/rectangle_871_x2.svg
  - assets/vectors/rectangle_951_x2.svg
  - assets/vectors/rectangle_97_x2.svg
  - assets/vectors/rectangle_991_x2.svg
  - assets/vectors/rectangle_81_x2.svg
  - assets/vectors/rectangle_86_x2.svg
  - assets/vectors/rectangle_911_x2.svg
  - assets/vectors/rectangle_981_x2.svg
  - assets/vectors/rectangle_88_x2.svg
  - assets/vectors/rectangle_921_x2.svg
  - assets/vectors/rectangle_841_x2.svg
  - assets/vectors/rectangle_931_x2.svg
  - assets/images/rectangle_472.png
  - assets/images/image_13.png
  - assets/vectors/rectangle_84_x2.svg
  - assets/vectors/rectangle_82_x2.svg
  - assets/vectors/rectangle_99_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/rectangle_98_x2.svg
  - assets/vectors/rectangle_92_x2.svg
  - assets/vectors/rectangle_971_x2.svg
  - assets/vectors/rectangle_901_x2.svg
  - assets/vectors/rectangle_83_x2.svg
  - assets/vectors/rectangle_93_x2.svg
  - assets/vectors/rectangle_941_x2.svg
  - assets/vectors/rectangle_891_x2.svg
  - assets/vectors/rectangle_811_x2.svg
  - assets/vectors/rectangle_87_x2.svg
  - assets/vectors/rectangle_881_x2.svg
  - assets/vectors/rectangle_851_x2.svg
  - assets/vectors/rectangle_80_x2.svg
  - assets/vectors/rectangle_91_x2.svg
  - assets/vectors/rectangle_961_x2.svg
  - assets/vectors/rectangle_861_x2.svg
  - assets/vectors/rectangle_95_x2.svg
  - assets/images/rectangle_47.jpeg
  - assets/images/rectangle_63.png
  - assets/images/rectangle_511.png
  - assets/images/rectangle_61.jpeg
  - assets/images/rectangle_60.png
  - assets/images/rectangle_62.jpeg
  - assets/images/image_13.png
  - assets/images/rectangle_472.png
  - assets/images/rectangle_471.jpeg
  - assets/vectors/vector_35_x2.svg
  - assets/images/image_13.png
  - assets/images/rectangle_33.jpeg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/images/image_13.png
  - assets/images/rectangle_331.jpeg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/pattern_x2.svg
  - assets/vectors/pattern_1_x2.svg
  - assets/images/rectangle_51.jpeg
  - assets/images/image_13.png
  - assets/vectors/vector_41_x2.svg
  - assets/images/rectangle_110.jpeg
  - assets/images/image_13.png
  - assets/vectors/dictation_x2.svg
  - assets/vectors/rectangle_9_x2.svg
  - assets/vectors/emoji_2_x2.svg
  - assets/vectors/rectangle_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/shift_2_x2.svg
  - assets/vectors/rectangle_1_x2.svg
  - assets/images/image_13.png
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/images/ellipse_8.jpeg
  - assets/images/ellipse_7.jpeg
  - assets/images/image_13.png
  - assets/images/rectangle_331.jpeg
  - assets/images/rectangle_116.jpeg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/ellipse_81_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/images/rectangle_60.png
  - assets/images/rectangle_62.jpeg
  - assets/images/rectangle_511.png
  - assets/images/rectangle_61.jpeg
  - assets/images/image_13.png
  - assets/images/rectangle_63.png
  - assets/images/rectangle_331.jpeg
  - assets/vectors/group_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/images/rectangle_60.png
  - assets/images/rectangle_471.jpeg
  - assets/images/rectangle_472.png
  - assets/images/rectangle_511.png
  - assets/images/image_13.png
  - assets/images/rectangle_47.jpeg
  - assets/images/rectangle_61.jpeg
  - assets/images/rectangle_62.jpeg
  - assets/images/rectangle_63.png
  - assets/vectors/vector_18_x2.svg
  - assets/images/image_3.png
  - assets/vectors/battery_x2.svg
  - assets/vectors/mobile_signal_x2.svg
  - assets/vectors/wifi_x2.svg

